AWSTemplateFormatVersion: 2010-09-09
Description: This template will create security group
 
Resources:
  AllowAllTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This group will allow all HTTP and SSH traffic
      GroupName: AllowAllTraffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
